// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOGssuSRhpZSZD0vr9Tcp6oIVeeMaXn',
    appId: '1:376938251781:web:b5cbd00a783982206afe6c',
    messagingSenderId: '376938251781',
    projectId: 'family-star-8be98',
    authDomain: 'family-star-8be98.firebaseapp.com',
    storageBucket: 'family-star-8be98.firebasestorage.app',
    measurementId: "G-R8MN1VL87G"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAQcKxuYd7IEPwuls7Epq38cQszJhs4ME', // Provient de "current_key"
    appId: '1:376938251781:android:277085dc16c143d06afe6c', // Provient de "mobilesdk_app_id"
    messagingSenderId: '376938251781', // Provient de "project_number"
    projectId: 'family-star-8be98', // Provient de "project_id"
    storageBucket: 'family-star-8be98.appspot.com', // Construit à partir de "project_id"
);

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.familyStar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.familyStar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOGssuSRhpZSZD0vr9Tcp6oIVeeMaXn',
    appId: '1:376938251781:web:b5cbd00a783982206afe6c',
    messagingSenderId: '376938251781',
    projectId: 'family-star-8be98',
    authDomain: 'family-star-8be98.firebaseapp.com',
    storageBucket: 'family-star-8be98.firebasestorage.app',
    measurementId: "G-R8MN1VL87G"
  );
}